#!/usr/bin/env bash

set -e

DEFAULT_CONFIG_PREFIX="default"
CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

# Example input
input_string="$*"

# Use IFS to split the string based on '--'
# Replace '--' with a special delimiter (newline or space)
input_string="${input_string//--/|}"
IFS='|' read -ra parts <<< "$input_string"

modules="${parts[0]}"

# If there's a second part, store it as 'args'; otherwise, 'args' is an empty string
if [[ ${#parts[@]} -gt 1 ]]; then
    args="--${parts[1]}"
else
    args=""
fi

for conf in ${DEFAULT_CONFIG_PREFIX} ${modules}; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${conf}${CONFIG_SUFFIX}" ${args}
done
