[manager]
linemode = "size_and_mtime"
show_hidden = false
show_symlink = true

[preview]
# Change them to your desired values
max_width = 2000
max_height = 2000

[opener]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = 'iina "$@"', desc = "iina", orphan = true },
]
