name: basic CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  build-and-run-pytest:

    runs-on: ubuntu-latest

    steps:
      # First step (unnamed here) is to checkout to the branch that triggered the event
      - uses: actions/checkout@v3

      # Second step: run pre-commit hooks
      - uses: pre-commit/action@v3.0.1

      # Third step: install python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Fourth step: install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.9"

      # Fifth step: install
      - name: Install packages
        run: uv sync --frozen

      # Sixth step: run tests with Pytest
      - name: Run tests
        run: uv run pytest -v .
