# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast # Testing valid python code
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0  # Use the latest version available
    hooks:
      - id: mypy # Testing valid python static types code
        args: [--ignore-missing-imports, --install-types, --non-interactive]
  - repo: https://github.com/python-poetry/poetry
    rev: '2.0.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
      # run the linter
      - id: ruff
        args: [--extend-select, I, --fix ]
      # Run the formatter.
      - id: ruff-format
