# Starship configuration for Linux servers
# Minimal and fast prompt configuration

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$docker_context\
$line_break\
$character"""

[username]
style_user = "cyan bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = true
format = "@[$hostname](bold yellow) "
disabled = false

[directory]
style = "blue bold"
truncation_length = 3
truncate_to_repo = true
format = "in [$path]($style) "

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "purple bold"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[python]
symbol = " "
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "yellow bold"

[nodejs]
symbol = " "
format = "via [$symbol($version )]($style)"
style = "green bold"

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow)"