---
name: CI/CD

on:
  pull_request:
    branches:
      - [main, dev]

jobs:
  CI:
    runs-on: ubuntu-latest
    # INFO: When using self-hosted runners, mind the cache issue of uv
    # https://docs.astral.sh/uv/guides/integration/github/#caching

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pre-commit/action@v3.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install packages
        run: uv sync --frozen

      - name: Run tests
        run: uv run pytest -v .

      - name: Build documentation
        run: uv run mkdocs build

      - name: Verify documentation build
        run: |
          if [ ! -d "site" ]; then
            echo "Documentation build failed"
            exit 1
          fi
