---
name: ci/cd

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    # INFO: When using self-hosted runners, mind the cache issue of uv
    # https://docs.astral.sh/uv/guides/integration/github/#caching

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pre-commit/action@v3.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install packages
        run: uv sync --frozen

      - name: Run tests
        run: uv run pytest -v .

      - name: Build documentation
        run: uv run mkdocs build

      - name: Verify documentation build
        run: |
          if [ ! -d "site" ]; then
            echo "Documentation build failed"
            exit 1
          fi
  cd-main:
    # Only run this job if the "ci" job passes
    needs: ci

    # Only run this job if new work is pushed to the "main" branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Python Semantic Release to prepare release
        id: release
        uses: python-semantic-release/python-semantic-release@v8.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  cd-dev:
    # Only run this job if the "ci" job passes
    needs: ci

    # Only run this job if new work is pushed to the "dev" branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Python Semantic Release to prepare release
        id: release
        uses: python-semantic-release/python-semantic-release@v8.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
