---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # Testing valid python code
    rev: v4.0.1
    hooks:
      - id: check-ast
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      # Testing valid python static types code
      - id: mypy
        args: [--ignore-missing-imports, --install-types, --non-interactive]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: '0.7.2'
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.11.2'
    hooks:
      # run the linter
      - id: ruff
        args: [--extend-select, I, --fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/compilerla/conventional-pre-commit
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
