return {
	-- {
	-- 	"benlubas/molten-nvim",
	-- 	version = "^1.0.0", -- use version <2.0.0 to avoid breaking changes
	-- 	dependencies = { "3rd/image.nvim" },
	-- 	build = ":UpdateRemotePlugins",
	-- 	init = function()
	-- 		-- these are examples, not defaults. Please see the readme
	-- 		vim.g.molten_image_provider = "image.nvim"
	-- 		vim.g.molten_output_win_max_height = 20
	-- 	end,
	-- },
	--
	-- {
	-- 	"3rd/image.nvim",
	-- 	dependencies = {
	-- 		"leafo/magick",
	-- 	},
	-- 	opts = {
	-- 		{
	-- 			max_width = 100, -- tweak to preference
	-- 			max_height = 12, -- ^
	-- 			max_height_window_percentage = math.huge, -- this is necessary for a good experience
	-- 			max_width_window_percentage = math.huge,
	-- 			window_overlap_clear_enabled = true,
	-- 			window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
	-- 		},
	-- 	},
	-- },
}
