# official docs at: https://espanso.org/docs/

matches:
  # Anrede
  - trigger: "!sehr"
    replace: "Sehr Geehrte,\n\n"
  # Print the current date in ISO Format
  - trigger: "!odate"
    replace: "{{odate}}"
    vars:
      - name: odate
        type: date
        params:
          format: "%F"
